emperors = [['Aemilian', 'Marcus Aemilius Aemilianus'],
 ['Alexander III'],
 ['Alexander Severus'],
 ['Alexios III'],
 ['Alexios II Komnenos', 'Alexius II Comnenus'],
 ['Alexios IV'],
 ['Alexios I Komnenos'],
 ['Alexios V'],
 ['Allectus'],
 ['Anastasios II', 'Anastasius II'],
 ['Anastasius', 'Anastasius I'],
 ['Andronikos III'],
 ['Andronikos II'],
 ['Andronikos IV'],
 ['Andronicus I Comnenus', 'Andronikos I Komnenos'],
 ['Andronikos V'],
 ['Anthemius'],
 ['Antoninus Pius'],
 ['Arcadius'],
 ['Areobindus'],
 ['Artabasdos'],
 ['Augustus', 'Gaius Julius Caesar Octavianus'],
 ['Aurelian', 'Lucius Domitius Aurelianus'],
 ['Aureolus'],
 ['Avidius Cassius'],
 ['Avitus', 'Eparchius Avitus'],
 ['Basil II'],
 ['Basil I'],
 ['Basiliscus'],
 ['Bonosus'],
 ['Caligula', 'Gaius', 'Gaius Caesar Augustus Germanicus'],
 [' Marcus Aurelius Antoninus', 'Caracalla', 'Lucius Septimius Bassianus'],
 ['Carausius'],
 ['Carinus'],
 ['Carus'],
 ['Claudius', 'Ti. Claudius Nero Germanicus'],
 [' Claudius II', 'Claudius Gothicus', 'M. Aurelius Claudius'],
 ['Clodius Albinus'],
 ['Comentiolus'],
 ['Commodus', 'Marcus Aurelius Commodus Antoninus'],
 ['Constans I', 'Flavius Julius Constans'],
 ['Constans II'],
 [],
 ['Constantine III'],
 ['Constantine III'],
 ['Constantine II', 'Flavius Claudius Constantinus'],
 ['Constantine IV'],
 ['Constantine IX'],
 ['Contantine (XI)'],
 ['Constantine V', 'Constantine V Copronymus'],
 ['Constantine VI', 'Constantine Vi'],
 ['Constantine VII'],
 ['Constantine VIII'],
 ['Constantine XI'],
 ['Constantine X Doukas'],
 ['Constantine I', 'Flavius Valerius Constantinus'],
 ['Constantius Chlorus', 'Constantius I Chlorus'],
 ['Constantius II', 'Flavius Julius Constantius'],
 ['Constantius III'],
 [' Gaius Messius Quintus Decius', 'Decius', 'Trajan Decius'],
 ['Diadumenian', 'Diadumenianius'],
 ['Didius Julianus', 'Marcus Didius Severus Julianus'],
 ['Diocletian'],
 ['Domitian', 'Titus Flavius Domitianus'],
 ['Domitianus II'],
 ['Domitius Alexander'],
 ['Elagabalus', 'Marcus Aurelius Antoninus'],
 ['Eleutherius'],
 ['Eugenius'],
 ['Flavius Valerius Severus', 'Severus II'],
 ['Flavius Victor'],
 [' Marcus Annius Florianus', 'Florian', 'Florianus'],
 ['Priscus'],
 ['Galba'],
 ['Caius Galerius Valerius Maximianus', 'Galerius'],
 ['Gallienus', 'P. Licinius Egnatius Gallienus'],
 ['Glycerius'],
 ['Gordian I'],
 ['Gordian II'],
 ['Gordian III'],
 ['Flavius Gratianus', 'Gratian'],
 ['Gregory'],
 ['Hadrian'],
 ['Heraclius'],
 ['Heraklonas'],
 ['Herennius Etruscus'],
 ['Flavius Honorius', 'Honorius'],
 ['Hostilian'],
 ['Hypatius'],
 ['Ingenuus'],
 ['Irene of Athens'],
 ['Isaac II'],
 ['Isaac I Komnenos'],
 ['Joannes'],
 ['John Athalarichos'],
 ['John Cottistis'],
 ['John III'],
 ['John II Comnenus', 'John II Komnenos'],
 ['John IV'],
 ['John I'],
 ['John VIII'],
 ['John VII'],
 ['John VI'],
 ['John V'],
 ['John of Conza'],
 ['Jotapianus'],
 ['Flavius Jovianus', 'Jovian'],
 ['Jovinus'],
 [' Flavius Claudius Julianus', 'Julian', 'Julian The Apostate'],
 ['Julianus ben Sabar'],
 ['Julius Nepos'],
 ['Julius Saturninus'],
 ['Justin I'],
 ['Justin II'],
 ['Justinian', 'Justinian I'],
 ['Justinian II'],
 ['Laelianus'],
 ['Leo III'],
 ['Leo II'],
 ['Leo IV', 'Leo Iv'],
 ['Leo I'],
 ['Leo VI'],
 ['Leo V'],
 ['Leontios'],
 ['Leontius'],
 ['Libius Severus'],
 ['Licinianus'],
 ['Licinius', 'Valerius Licinianus Licinius'],
 ['Longinus'],
 ['Lucius Verus'],
 ['Macrianus Major'],
 ['Macrianus Minor'],
 ['Macrinus', 'Marcus Opellius Macrinus'],
 ['Magnentius'],
 ['Magnus Maximus'],
 ['Julius Valerius Maiorianus', 'Majorian'],
 ['Manuel II', 'Manuel II Palaiologos'],
 ['Manuel I Comnenus', 'Manuel I Komnenos'],
 ['Marcian'],
 ['Marcus Aurelius'],
 ['Marius'],
 ['M. Aurelius Probus', 'Probus'],
 ['Marcus Claudius Tacitus', 'Tacitus'],
 ['Matthew'],
 ['Maurice'],
 ['Maurikios Chartoularios'],
 ['Marcus Aurelius Valerius Maxentius', 'Maxentius'],
 ['Maximian', 'Maximianus Herculius'],
 ['Caius Valerius Galerius Maximinus', 'Maximinus Daia'],
 ['Maximinus Thrax'],
 ['Maximus'],
 ['Mezezius'],
 ['Michael II'],
 ['Michael III'],
 ['Michael IV'],
 ['Michael IX'],
 ['Michael I Rangabe'],
 ['Michael V'],
 ['Michael VIII'],
 ['Michael VII Doukas'],
 ['Michael VI'],
 ['Mussius Aemilianus'],
 ['Nepotianus'],
 ['Nero'],
 ['Nerva'],
 ['Nikephoros I'],
 ['Nikephoros III (Botaneiates)'],
 ['Nikephoros II'],
 ['Numerian', 'Numerianus'],
 ['Ancius Olybrius', 'Olybrius'],
 ['Olympius'],
 ['Otho'],
 ['Pacatianus'],
 ['Pertinax', 'Publius Helvius Pertinax'],
 ['Pescennius Niger'],
 ['Petronius Maximus'],
 ['Marcus Julius Philippus', 'Philip the Arab'],
 ['Philippikos Bardanes'],
 ['Phocas'],
 ['Postumus'],
 ['Priscus Attalus'],
 ['Procopius'],
 ['Proculus'],
 ['Geta', 'Publius Septimius Geta'],
 ['Pupienus'],
 ['Quietus'],
 ['Quintillus'],
 ['Regalianus'],
 ['Romanos II'],
 ['Romanos III'],
 ['Romanos IV (Doukas)'],
 ['Romanos I'],
 ['Romulus Augustulus', 'Romulus Augustus'],
 ['Sabinianus'],
 ['Saborios'],
 ['Saloninus'],
 ['Sebastianus'],
 ['Septimius'],
 ['Lucius Septimius Severus', 'Septimius Severus'],
 ['Sextus Martinianus'],
 ['Silbannacus'],
 ['Staurakios'],
 ['Stotzas'],
 ['Tetricus I'],
 ['Theocritus'],
 ['Theodora'],
 ['Theodore II'],
 ['Theodore I'],
 ['Theodoros Pasagnathes'],
 ['Theodosios III', 'Theodosius III'],
 ['Flavius Theodosius', 'Theodosius I'],
 ['Theodosius II'],
 ['Theophilos'],
 ['Tiberius', 'Tiberius Claudius Nero'],
 ['Tiberius II Constantine'],
 ['Titus', 'Titus Flavius Vespasianus'],
 ['Trajan'],
 ['Gallus'],
 ['Flavius Valens', 'Valens'],
 ['Flavius Valentinianus', 'Valentinian I'],
 ['Valentinian II'],
 ['Valentinian III'],
 ['Valentinus'],
 ['P. Licinius Valerianus', 'Valerian'],
 ['Valerius Valens'],
 ['Titus Flavius Vespasianus', 'Vespasian'],
 ['Vetranio'],
 ['Victorinus'],
 ['Vitellius'],
 ['Volusianus'],
 ['Zeno'],
 ['Zoe', 'Zoe Porphyrogenita']]
